
version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@1.0.0

jobs:
  find_changed_packages:
    docker:
      - image: cimg/node:14.15
    resource_class: large

    steps:
      - checkout
      - run:
          name: Run Find Changed Packages Script
          command: |
            find ./packages -mindepth 1 -maxdepth 1 -type d '!' -exec test -e "{}/package.json" ';' -print \
              | xargs --no-run-if-empty rm -r

      - run: yarn config set ignore-engines true

      - run: yarn config set cache-folder /mnt/ramdisk/yarn-cache

        # Yarn has some random race-condition failures, trying multiple times seems to help
        # when the source of the problem is yarn itself and not the packages
      - run: yarn || yarn || yarn
      - run:
          name: Compile and Run Find Changed Packages Script
          command: |
            pushd .circleci/scripts
            node find_changed_packages.js
            node update_config_template.js
      - persist_to_workspace:
          root: .
          paths:
            - .circleci/continue_config.yml
  

workflows:
  commit:
    jobs:
      - find_changed_packages
      - continuation/continue:
          requires:
            - find_changed_packages
          checkout: false
          configuration_path: .circleci/continue_config.yml
          workspace_path: .
