
version: 2.1

setup: true

setup: true

orbs:
  continuation: circleci/continuation@1.0.0
  continuation: circleci/continuation@1.0.0

jobs:
  find_changed_packages:
  find_changed_packages:
    docker:
      - image: cimg/node:14.15
    resource_class: large
    resource_class: large

    steps:
      - checkout
      - run:
          name: Compile and Run Find Changed Packages Script
          command: |
            pushd .circleci/scripts
            node find_changed_packages.js
            node update_config_template.js
      - persist_to_workspace:
          root: .
          paths:
            - .circleci/continue_config.yml
  
            - .circleci/continue_config.yml
  

workflows:
  commit:
    jobs:
      - find_changed_packages
      - continuation/continue:
      - find_changed_packages
      - continuation/continue:
          requires:
            - find_changed_packages
          checkout: false
          configuration_path: .circleci/continue_config.yml
          workspace_path: .
